config/routes.rb
ClientApp::Application.routes.draw do

  devise_for :users do
    root :to => 'home#index'
  end
  get "home/index"
  resources :client_applications
  resources :users
  root :to => 'home#index'

  match "add_attachments" => "client_applications#add_attachments"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if !current_user.blank?
      if current_user.admin?
        redirect_to client_applications_path
        flash[:notice] = "Welcome to the Admin Client Application listing"
      end
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/finished.html.haml
%center
  %h2 Thank you for your application!
  %br
  %h3
    = link_to 'Click here', 'http://www.isotope11.com'
    if you would like to be redirected back to the Isotope11.com
  %center
    or
  %h3
    = link_to 'Click here', new_client_application_path
    if you would like to get an estimate on your project

app/views/home/index.html.haml
%h1.title Isotope11 Client Applications
.content
  - if current_user
    - if current_user.admin?
      = link_to "View Client Applications", client_applications_path
    - else
      - if current_user.client_application.application_state == "submitted"
        %h3 Your application has been submitted!
        .submitted
          %h3
            Application Progress:
            = "#{current_user.client_application.progress}%"
          = progress_bar(current_user.client_application.progress, :rounded => true, :color => "blue") 
          %p
          Isotope11 is currently reviewing your application, and will email when further information is required.
          %p
      - if current_user.client_application.application_state == "requested"
        %h3 We need more information!
        .requested
          %h3
            Application Progress:
            = "#{current_user.client_application.progress}%"
          = progress_bar(current_user.client_application.progress, :rounded => true, :color => "blue") 
          %p
          Isotope11 has reviewed your application, and needs more information from you.
          %p
          = link_to 'Continue Application.', edit_client_application_path(current_user.client_application), :class => "btn success"
      - if current_user.client_application.application_state == "responded"
        %h3 You have responded to Isotope's request!
        .responded
          %h3
            Application Progress:
            = "#{current_user.client_application.progress}%"
          = progress_bar(current_user.client_application.progress, :rounded => true, :color => "blue") 
          %p
          Isotope will now finish processing your application.
          %p
          Please be patient as this could take a few days. You will receive an email when complete.
          %p
      - if current_user.client_application.application_state == "completed"
        %h3 Your application is complete!
        .completed
          %h3
            Application Progress:
            = "#{current_user.client_application.progress}%"
          = progress_bar(current_user.client_application.progress, :rounded => true, :color => "blue") 
          %p
          Isotope11 has received your completed application!
          %p
          We will contact you soon.
  - else
    %h3 Click below to start a new application:
    = link_to "New Application", new_client_application_path, :class => "btn info"