config/routes.rb
ClientApp::Application.routes.draw do

  devise_for :users do
    root :to => 'home#index'
  end
  get "home/index"
  resources :client_applications
  resources :users
  root :to => 'home#index'

  match "add_attachments" => "client_applications#add_attachments"

end

app/models/client_application.rb
class ClientApplication < ActiveRecord::Base

  attr_encrypted :password, :key => 'client_app'

  validates_uniqueness_of :email, :business_name
  validates_presence_of :business_name, :first_name, :last_name, :email, :phone_number, :years_in_business, :number_of_employees, :business_address, :billing_address, :city, :zip, :business_type, :revenue
  validates_presence_of :password, :on => :create
  validates_format_of :email, :with => /(\S+)@(\w+.\w+)/

  belongs_to :user
  belongs_to :state
  has_many :attachments, :dependent => :destroy
  has_many :principal_information_forms, :dependent => :destroy
  has_many :banking_information_forms, :dependent => :destroy
  accepts_nested_attributes_for :attachments, :allow_destroy => true
  accepts_nested_attributes_for :principal_information_forms, :allow_destroy => true
  accepts_nested_attributes_for :banking_information_forms, :allow_destroy => true

  # State Machine set up for client applications
  state_machine :application_state, :initial => :incomplete do
    after_transition :incomplete => :submitted, :do => :after_submit
    after_transition :submitted => :requested, :do => :after_request
    after_transition :requested => :responded, :do => :after_respond
    after_transition :responded => :completed, :do => :after_complete

    event :submit do
      transition [:incomplete, :responded] => :submitted
    end

    event :requesting do
      transition [:submitted] => :requested
    end

    event :respond do
      transition [:requested] => :responded
    end

    event :complete do
      transition [:responded] => :completed
    end

    state :incomplete
    state :submitted
    state :requested
    state :responded
    state :completed
  end

  def after_submit
    Client.isotope_email(self).deliver
  end

  def after_request
    Client.client_email(self).deliver
  end

  def after_respond
    Client.isotope_email(self).deliver
  end

  def after_complete
    Client.completed_email(self).deliver
    # send json request to Xrono to create a Client
    XronoImport.new.send_client(self)
  end

end

app/controllers/client_applications_controller.rb
class ClientApplicationsController < ApplicationController

  before_filter :admin_required, :only => [:index, :show, :destroy]
  before_filter :login_required, :only => [:edit]

  def index
    @client_applications = ClientApplication.all
  end

  def show
    @client_application = ClientApplication.find(params[:id])
  end

  def new
    @client_application = ClientApplication.new
  end

  def create
    @client_application = ClientApplication.new(params[:client_application])
    if @client_application.save
      @client_application.submit!
      @client_application.update_attributes(:progress => 25)
      @user = User.new(:email => @client_application.email, :password => @client_application.password, :password_confirmation => @client_application.password )
      if @user.save
        # would like to refactor here!!
        @client_application.update_attributes(:user_id => @user.id)
        redirect_to "/"
        flash[:notice] = "Application submitted successfully"
      end
    else
      render 'new'
      error_message = @client_application.errors.full_messages.first
      flash[:error] = error_message
    end
  end

  def edit
    @client_application = ClientApplication.find(params[:id])
    if !verify_user
      redirect_to root_path
    else
      unless @client_application.principal_information_forms.present?
        @principal_information_form = @client_application.principal_information_forms.build
      end
      unless @client_application.banking_information_forms.present?
        @banking_information_form = @client_application.banking_information_forms.build
      end
#      @selected = @client_application.attributes.select{|k, v| v == true}
      @selected = @client_application.attributes.select{|k, v| v == true && k != "returned" && k != "contact_by_email"}
      unless @selected.empty?
        @selected.each do |param|
         @client_application.attachments.find_or_create_by_description(param.first)
        end
      end
      render @client_application.application_state
    end
  end

  def update
    @client_application = ClientApplication.find(params[:id])
    update_state
  end

  def destroy
    @client_application = ClientApplication.find(params[:id])
    @client_application.destroy
    redirect_to :back
    flash[:notice] = "Client Application successfully deleted"
  end

  def update_state
    # fix me - needs to not update attributes if they already exists... it is currently overwriting old values to add new ones.
    @client_application.update_attributes(params[:client_application])
    if @client_application.application_state == "submitted"
      @client_application.requesting!
      @client_application.update_attributes(:progress => 50)
      message = "This application has been sent in for request"
    elsif @client_application.application_state == "requested"
      @client_application.respond!
      @client_application.update_attributes(:progress =>  75)
      message = "This application has been sent in for response"
    elsif @client_application.application_state == "responded"
      if @client_application.returned?
        @client_application.submit!
        @client_application.update_attributes(:progress => 25)
        message = "This application has been flagged for further review."
      else
        @client_application.complete!
        @client_application.update_attributes(:progress => 100)
        message = "This application is complete"
      end
    end
    redirect_to "/"
    flash[:notice] = message
  end

  def add_attachments
     @client_application = ClientApplication.find(params[:application_id])
     update_state
  end

  def verify_user
    @client_application.user == current_user || current_user.admin?
  end


end

app/helpers/client_applications_helper.rb
module ClientApplicationsHelper
end

app/views/client_applications/_banking_information_form.html.haml
- if @client_application.banking_information?
  %fieldset
    %legend
      Banking Information
    = f.fields_for :banking_information_forms do |b|
      .clearfix
        = b.label 'Bank Name'
        .input= b.text_field :bank_name
      .clearfix
        = b.label 'Bank Address'
        .input= b.text_field :bank_address
      .clearfix
        = b.label 'Contact Person'
        .input= b.text_field :contact_person
      .clearfix
        = b.label 'Bank Phone Number'
        .input= b.text_field :phone_number
      .clearfix
        = b.label 'Previous Banking Institution'
        .input= b.text_field :previous_bank

app/views/client_applications/_form.html.haml
.form_wrapper
  = form_for(@client_application) do |f|
    - if @client_application.errors.any?
      #error_explanation
        %h2
          = pluralize(@client_application.errors.count, "error")
          prohibited this application from being saved:
        %ul
          - @client_application.errors.full_messages.each do |msg|
            %li= msg

    %fieldset.business_info
      %legend
        Business Information
      .clearfix
        = f.label 'Business Name*'
        .input= f.text_field :business_name 
      .clearfix
        = f.label 'Contact Name (First)*'
        .input= f.text_field :first_name 
      .clearfix
        = f.label 'Contact Name (Last)*'
        .input= f.text_field :last_name 
      .clearfix
        = f.label 'Email*'
        .input= f.text_field :email
      .clearfix
        = f.label 'Password* (minimum 6 characters)'
        .input= f.password_field :password
      .clearfix
        = f.label 'Phone number*'
        .input= f.text_field :phone_number
      .clearfix
        = f.label 'Years in Business*'
        .input= f.text_field :years_in_business, :class => "text"
      .clearfix
        = f.label 'Number of Employees*'
        .input= f.text_field :number_of_employees, :class => "text"
      .clearfix
        = f.label 'Most recent fiscal year revenue*'
        .input= f.text_field :revenue, :class => "text"
      .clearfix
        = f.label 'DBA Name'
        .input= f.text_field :dba_name 
      .clearfix
        = f.label 'Parent Company'
        .input= f.text_field :parent_company
      .clearfix
        = f.label 'Taxpayer ID number'
        .input= f.text_field :taxpayer_id_number
      .clearfix
        = f.label 'Business Website'
        .input= f.text_field :business_website

    %fieldset.business_location
      %legend
        Business Location
      .clearfix
        = f.label 'Primary Business Address*'
        .input= f.text_field :business_address
      .clearfix
        = f.label 'Billing Address*'
        .input= f.text_field :billing_address
      .clearfix
        = f.label 'City*'
        .input= f.text_field :city
      .clearfix
        = f.label 'State*'
        .input= f.select(:state_id, options_from_collection_for_select(State.all, :id, :name))
      .clearfix
        = f.label 'Zip code*'
        .input= f.text_field :zip, :maxlength => 5, :class => "text"

    %fieldset.business_type
      %legend
        Preferred Contact Method
      .clearfix
        .input
          %ul.inputs-list
            %label
              = f.radio_button :contact_by_email, 1
              %span Email
            %label
              = f.radio_button :contact_by_email, 0
              %span Phone

    %fieldset.business_type
      %legend
        Business Type
      .clearfix
        .input
          %ul.inputs-list
            %label
              = f.radio_button :business_type, "private_corp", :class => "private_corp"
              %span Private Corporation
            %label
              = f.radio_button :business_type, "public_corp", :class => "public_corp"
              %span Public Corporation
            %label
              = f.radio_button :business_type, "partnership", :class => "no_field"
              %span Partnership
            %label
              = f.radio_button :business_type, "non_profit", :class => "no_field"
              %span Non-Profit
            %label
              = f.radio_button :business_type, "sole_proprietor", :class => "no_field"
              %span Sole Proprietor
            %label
              = f.radio_button :business_type, "other", :class => "other_corp"
              %span Other

      .clearfix.private_corp_type
        = f.label 'Private Corporation Type'
        .input= f.text_field :private_corp_type
      .clearfix.market_symbol
        = f.label 'Market Symbol'
        .input= f.text_field :market_symbol
      .clearfix.other_field
        = f.label 'Business Type:'
        .input= f.text_field :other_type

    %fieldset.business_info
      .clearfix
        = f.label 'Project Description/Scope'
        .input= f.text_area :project_description

    %fieldset.business_type
      %legend
        Attachments:
      .clearfix
        = f.fields_for :attachments do |a|
          .input= a.file_field :document

    .actions
      = f.submit :class => 'btn primary'
      = link_to 'Back', client_applications_path, :class => 'btn'

:javascript
  $(document).ready(function(){

    $('.other_field').hide();
    $('.private_corp_type').hide();
    $('.market_symbol').hide();

    $('.other_corp').click(function(){
      if ($(this).attr("checked") == "checked") {
        $(".private_corp_type").hide();
        $(".market_symbol").hide();
        $(".other_field").fadeIn("slow");
      }
      else {
        $(".other_field").fadeOut("slow");
      }
    });

    $('.public_corp').click(function(){
      if ($(this).attr("checked") == "checked") {
        $(".other_field").hide();
        $(".private_corp_type").hide();
        $(".market_symbol").fadeIn("slow");
      }
      else {
        $(".market_symbol").fadeOut("slow");
      }
    });

    $('.private_corp').click(function(){
      if ($(this).attr("checked") == "checked") {
        $(".other_field").hide();
        $(".market_symbol").hide();
        $(".private_corp_type").fadeIn("slow");
      }
      else {
        $(".market_symbol").fadeOut("slow");
      }
    });

    $('.no_field').click(function(){
      $(".other_field").fadeOut("slow");
      $(".private_field_type").fadeOut("slow");
      $(".market_symbol").fadeOut("slow");
    });

  });

app/views/client_applications/_litigation_information_form.html.haml
- if @client_application.litigation_information?
  %fieldset
    %legend
      Litigation Form
    %span
      %h5 Have you or your company been involved in any litigation in the past 5 years?
      = 'No'
      = radio_button_tag 'litigation', "no", :checked => true
      = 'Yes'
      = radio_button_tag 'litigation', "yes"
    .litigation_fields
      %h5 Please describe the nature of the litigation and upload any documents.
      .clearfix
        = f.text_area :litigation_description, :class => 'xxlarge'

app/views/client_applications/_principal_information_form.html.haml
- if @client_application.principal_information?
  %fieldset
    %legend
      Principal Information Form
    = f.fields_for :principal_information_forms do |p|
      .personal_info
        %h5 Personal Information
        .clearfix
          = p.label 'Name'
          .input= p.text_field :name
        .clearfix
          = p.label 'Alternate Name'
          .input= p.text_field :alternate_name
        .clearfix
          = p.label 'Social Security Number'
          .input= p.text_field :ssn
        .clearfix
          = p.label 'Date of Birth'
          .input= p.text_field :dob
        .clearfix
          = p.label 'Drivers License Number'
          .input= p.text_field :dl_number
        .clearfix
          = p.label 'Drivers License State'
          .input= p.text_field :dl_state
      %p

      .employment_info
        %h5 Employment Status
        .clearfix
          = p.label 'Position'
          .input= p.text_field :position
        .clearfix
          = p.label 'Company'
          .input= p.text_field :company
        .clearfix
          = p.label 'Years with Company'
          .input= p.text_field :years_with_company
        .clearfix
          = p.label 'Previous Employer'
          .input= p.text_field :prev_employer
        .clearfix
          = p.label "Today's Date"
          .input= p.text_field :date
      %p

      .address_info
        %h5 Address Information
        %p
        .clearfix
          = p.label 'Street Address'
          .input= p.text_field :street_address
        .clearfix
          = p.label 'City'
          .input= p.text_field :city
        .clearfix
          = p.label 'State'
          .input= p.text_field :state
        .clearfix
          = p.label 'Zip Code'
          .input= p.text_field :zip
        .clearfix
          = p.label 'County'
          .input= p.text_field :county
        %p

        %h5 Have you lived at your current address for more than 3 years?
        %p
        %span
          = 'Yes'
          = radio_button_tag 'address', "yes", :checked => true
          = 'No'
          = radio_button_tag 'address', "no"
        .prev_address_fields
          %h5 Previous Address Information
          .clearfix
            = p.label 'Previous Street Address'
            .input= p.text_field :prev_street_address
          .clearfix
            = p.label 'Previous City'
            .input= p.text_field :prev_city
          .clearfix
            = p.label 'Previous State'
            .input= p.text_field :prev_state
          .clearfix
            = p.label 'Previous Zip'
            .input= p.text_field :prev_zip
          .clearfix
            = p.label 'Previous County'
            .input= p.text_field :prev_county

app/views/client_applications/_requested_information_form.html.haml
%fieldset
  = f.fields_for :attachments, :html => { :multipart => true } do |a|
    - if a.object[:document_file_name].present?
      .clearfix
        = a.label a.object[:description]
        %h4.input= a.object[:document_file_name]
    - else
      .clearfix
        = a.label a.object[:description]
        .input= a.file_field :document

app/views/client_applications/_show_page.html.haml
%h1= @client_application.business_name

%h3
  Application Progress:
  = "#{@client_application.progress}%"
= progress_bar(@client_application.progress, :tiny => true,:color => "blue") 
%p
= link_to 'Back', root_path
|
= link_to 'Edit', edit_client_application_path(@client_application)
|
= link_to 'Print', '#', onclick: 'window.print();return false;'
%p

%table.bordered-table.zebra-striped
  %thead
    %tr
      %th
        %h3.header Client Information:
  %tbody
    %tr
      %th Business Name
      %td= @client_application.business_name
    %tr
      %th DBA Name
      %td= @client_application.dba_name
    %tr
      %th Parent Company
      %td= @client_application.parent_company
    %tr
      %th Taxpayer ID
      %td= @client_application.taxpayer_id_number
    %tr
      %th Years in Business
      %td= @client_application.years_in_business
    %tr
      %th Number of Employees
      %td= @client_application.number_of_employees
    %tr
      %th Business Website
      %td= @client_application.business_website
    %tr
      %th Preferred Contact Method
      - if @client_application.contact_by_email
        %td Phone
      - else
        %td Email
    %tr
      %th Business Address
      %td= @client_application.business_address
    %tr
      %th City
      %td= @client_application.city
    %tr
      %th State
      %td= State.find(@client_application.state_id).name
    %tr
      %th Zip code
      %td= @client_application.zip
    %tr
      %th Billing Address
      %td= @client_application.billing_address
    %tr
      %th Phone number
      %td= @client_application.phone_number
    %tr
      %th Email
      %td= @client_application.email


%table.bordered-table.zebra-striped
  %thead
    %tr
      %th
        %h3.header File Attachments:
  %tbody
    - @client_application.attachments.each do |attachment|
      %tr
        %th= attachment.description.titleize
        %td
          - if attachment.document_file_name
            = link_to attachment.document_file_name, attachment.document.url



- if !@client_application.principal_information_forms.empty? 
  %table.bordered-table.zebra-striped
    %thead
      %tr
        %th
          %h3.header Principal Information:
    %tbody
      %tr
        %th Name
        %td= @client_application.principal_information_forms.first.name
      %tr
        %th Alternate Name
        %td= @client_application.principal_information_forms.first.alternate_name
      %tr
        %th SSN
        %td= @client_application.principal_information_forms.first.ssn
      %tr
        %th DOB
        %td= @client_application.principal_information_forms.first.dob
      %tr
        %th Driver License Number
        %td= @client_application.principal_information_forms.first.dl_number
      %tr
        %th DL State
        %td= @client_application.principal_information_forms.first.dl_state
      %tr
        %th Street Address
        %td= @client_application.principal_information_forms.first.street_address
      %tr
        %th City
        %td= @client_application.principal_information_forms.first.city
      %tr
        %th State
        %td= @client_application.principal_information_forms.first.state
      %tr
        %th County
        %td= @client_application.principal_information_forms.first.county
      %tr
        %th Previous Street Address
        %td= @client_application.principal_information_forms.first.prev_street_address
      %tr
        %th Previous City
        %td= @client_application.principal_information_forms.first.prev_city
      %tr
        %th Previous State
        %td= @client_application.principal_information_forms.first.prev_state
      %tr
        %th Previous County
        %td= @client_application.principal_information_forms.first.prev_county
      %tr
        %th Position
        %td= @client_application.principal_information_forms.first.position
      %tr
        %th Company
        %td= @client_application.principal_information_forms.first.company
      %tr
        %th Years with Company
        %td= @client_application.principal_information_forms.first.years_with_company
      %tr
        %th Previous Employer
        %td= @client_application.principal_information_forms.first.prev_employer
      %tr
        %th Date
        %td= @client_application.principal_information_forms.first.date
      %tr
        %th Company
        %td= @client_application.principal_information_forms.first.street_address

- if !@client_application.banking_information_forms.empty? 
  %table.bordered-table.zebra-striped
    %thead
      %tr
        %th
          %h3.header Banking Information:
    %tbody
      %tr
        %th Bank Name
        %td= @client_application.banking_information_forms.first.bank_name
      %tr
        %th Bank Address
        %td= @client_application.banking_information_forms.first.bank_address
      %tr
        %th Contact Person
        %td= @client_application.banking_information_forms.first.contact_person
      %tr
        %th Phone Number
        %td= @client_application.banking_information_forms.first.phone_number
      %tr
        %th Previous Bank
        %td= @client_application.banking_information_forms.first.previous_bank
      %tr

- if @client_application.litigation_information?
  %table.bordered-table.zebra-striped
    %thead
      %tr
        %th
          %h3.header Litigation Information:
    %tbody
      %tr
        %th Litigation
        %td
          - if !@client_application.litigation_description.nil?
            = "Yes"
          - else
            = "No"
      %tr
        %th Litigation description
        %td=h truncate(@client_application.litigation_description, :length => 100)

app/views/client_applications/blank.html.haml
%h1 Blank application

= form_for @client_application do |f|
  = f.label "Blank"
  = f.text_field :business_name

  = f.submit "Submit"

app/views/client_applications/completed.html.haml
%h1 Completed

%h3 Congratulations! you have completed the application process. If you have any questions call someone at Isotope11.
%p
%center
  = link_to "Back to Isotope11.com", 'http://isotope11.com'

app/views/client_applications/index.html.haml
%h1.title Isotope11 Client Applications
.content
  %table.bordered-table.zebra-striped#table-sort
    %thead
      %tr
        %th Client company
        %th Client email
        %th App state
        %th Progress
        %th Created on
        %th edit
        %th delete
    %tbody
      - @client_applications.each do |app|
        %tr
          %td= link_to app.business_name, client_application_path(app)
          %td= app.email
          %td= app.application_state 
          %td= progress_bar(app.progress, :tiny => true, :color => "blue") 
          %td= app.created_at
          %td= link_to 'Edit', edit_client_application_path(app)
          %td= link_to 'Delete', app, :method => :delete, :confirm => "Delete this application?"

:javascript
  $(document).ready(function(){
    $("table#table-sort").tablesorter({ sortList: [[1,0]] });
  });

app/views/client_applications/new.html.haml
%h2 New Client Application
%br
= render 'form'

app/views/client_applications/requested.html.haml
%center
  %h1 Please provide the requested information and press submit:
  %h3 If you have any files to upload, please select them before submitting.

.form_wrapper
  = form_for @client_application, :html => { :multipart => true } do |f|
    = render 'banking_information_form', :f => f
    = render 'requested_information_form', :f => f, :application => @client_application
    = render 'principal_information_form', :f => f
    = render 'litigation_information_form', :f => f
    = f.submit "Submit", :class => "btn success"

:javascript
  $(document).ready(function(){
    $('.litigation_fields').hide();
    $('.prev_address_fields').hide();
    $('#litigation_yes').click(function(){
      $(".litigation_fields").fadeIn("slow");
    });
    $('#litigation_no').click(function(){
      $(".litigation_fields").fadeOut("slow");
    });
    $('#address_yes').click(function(){
      $(".prev_address_fields").fadeOut("slow");
    });
    $('#address_no').click(function(){
      $(".prev_address_fields").fadeIn("slow");
    });
  });

app/views/client_applications/responded.html.haml
= render 'show_page', :client_application => @client_application

%center
  %h2
    = form_for(@client_application) do |f|
      %span
        = f.radio_button :returned, 1
        = 'Request Additional information'
      %p
      %span
        = f.radio_button :returned, 0
        = 'Mark Application as complete (send to Xrono)'
      %p
      = f.submit "Submit"

app/views/client_applications/show.html.haml
= render 'show_page', :client_application => @client_application

app/views/client_applications/submitted.html.haml
%center
  %h1 Isotope11 - request information:
  %h2 Application Submitted

.form_wrapper
  = nested_form_for(@client_application, :url => { :controller => 'client_applications', :action => 'add_attachments', :method => :post}, :html => { :multipart => true }) do |f|
    %fieldset
      %legend
        Request Documents
      %span
        = hidden_field_tag :application_id, @client_application.id
      - unless @client_application.articles_of_incorporation?
        %span
          = f.check_box :articles_of_incorporation, :class => "documents"
          = 'Articles of Incorporation'
        %p
      - unless @client_application.proof_of_insurance?
        %span
          = f.check_box :proof_of_insurance, :class => "documents"
          = 'Proof of Insurance'
        %p
      - unless @client_application.business_license?
        %span
          = f.check_box :business_license, :class => "documents"
          = 'Business License'
        %p
      - unless @client_application.partnership_agreement?
        %span
          = f.check_box :partnership_agreement, :class => "documents"
          = 'Partnership Agreement'
        %p
      - unless @client_application.limited_partnership?
        %span
          = f.check_box :limited_partnership, :class => "documents"
          = 'Limited Partnership LP1'
        %p
      - unless @client_application.charter?
        %span
          = f.check_box :charter, :class => "documents"
          = 'Charter and By-Laws'
        %p
      - unless @client_application.association_resolution?
        %span
          = f.check_box :association_resolution, :class => "documents"
          = 'Association Resolution'
        %p
      - unless @client_application.irs_tax_exemption_form?
        %span
          = f.check_box :irs_tax_exemption_form, :class => "documents"
          = 'IRS Tax Exemption Status Form'
        %p
      - unless @client_application.bank_statements?
        %span
          = f.check_box :bank_statements, :class => "documents"
          = 'Bank Statement'
        %p
      - unless @client_application.tax_returns?
        %span
          = f.check_box :tax_returns, :class => "documents"
          = '2010 Tax Return'
        %p

    %fieldset
      %legend
        Request Forms
      - unless @client_application.principal_information?
        %span
          = f.check_box :principal_information, :class => "documents"
          = 'Principal Information form'
        %p
      - unless @client_application.banking_information?
        %span
          = f.check_box :banking_information, :class => "documents"
          = 'Banking Information form'
        %p
      - unless @client_application.litigation_information?
        %span
          = f.check_box :litigation_information, :class => "documents"
          = 'Litigation response'
        %p

    %fieldset
      %legend
        Additional Attachments
      = f.fields_for :attachments do |attachment|
        %span
          = attachment.text_field :description
          = attachment.link_to_remove "remove this task"
        %p
      = f.link_to_add "Add an attachment", :attachments

    = f.submit "Submit", :class => "btn success"